// <auto-generated />
namespace Biblioteca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Imagen_y_pdf_de_libros : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Imagen_y_pdf_de_libros));
        
        string IMigrationMetadata.Id
        {
            get { return "202201200131213_Imagen_y_pdf_de_libros"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
